#!/bin/sh

if [ "$1" = remove ]; then
    if [ -n "${CYDIA:-}" ]; then
        cydia_fd=${CYDIA%% *}
        eval "echo 'finish:restart' >&$cydia_fd"
    else
        echo "Please respring your device."
    fi
fi

exit 0
